
DROP TABLE IF EXISTS PUBLISHER;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS BOOK;


CREATE TABLE `PUBLISHER` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(100) NOT NULL,
	`ADDRESS` VARCHAR(300) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `AUTHOR` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`PUBLISHER_ID` INT NOT NULL,
	`NAME` VARCHAR(50) NOT NULL,
	`BIRTHDAY` CHAR(8) NOT NULL,
	`GENDER` CHAR(1) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `BOOK` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`AUTHOR_ID` INT NOT NULL,
	`TITLE` VARCHAR(200) NOT NULL,
	`PRICE` INT NOT NULL,
	PRIMARY KEY (`ID`)
);


INSERT INTO PUBLISHER(NAME, ADDRESS) VALUES ('pub_a', 'pub_addr_a');
INSERT INTO PUBLISHER(NAME, ADDRESS) VALUES ('pub_b', 'pub_addr_b');
INSERT INTO PUBLISHER(NAME, ADDRESS) VALUES ('pub_c', 'pub_addr_c');
INSERT INTO PUBLISHER(NAME, ADDRESS) VALUES ('pub_d', 'pub_addr_d');


INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (1, 'aut_1', '20000101', 'M');
INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (1, 'aut_2', '20011101', 'F');

INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (2, 'aut_4', '19900101', 'F');
INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (2, 'aut_5', '19920101', 'F');
INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (2, 'aut_6', '19900101', 'M');

INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (3, 'aut_7', '20000101', 'M');
INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (3, 'aut_8', '19951111', 'M');
INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (3, 'aut_9', '19901111', 'F');

INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (4, 'aut_3', '20001001', 'M');
INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (4, 'aut_1', '19970212', 'M');
INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (4, 'aut_5', '19970818', 'F');
INSERT INTO AUTHOR(PUBLISHER_ID, NAME, BIRTHDAY, GENDER) VALUES (4, 'aut_9', '19990909', 'M');


INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (1, 'bk_t_1', 3000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (1, 'bk_t_2', 5000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (1, 'bk_t_3', 4500);

INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (2, 'bk_t_4', 3500);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (2, 'bk_t_5', 5500);

INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (3, 'bk_t_6', 2000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (3, 'bk_t_7', 2500);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (3, 'bk_t_8', 3000);

INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (4, 'bk_t_9', 7000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (4, 'bk_t_10', 6000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (4, 'bk_t_11', 6500);

INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (5, 'bk_t_12', 5500);

INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (6, 'bk_t_13', 4000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (6, 'bk_t_14', 3000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (6, 'bk_t_15', 4500);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (6, 'bk_t_16', 5000);

INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (7, 'bk_t_17', 5500);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (7, 'bk_t_18', 6500);

INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (8, 'bk_t_19', 4000);

INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (9, 'bk_t_20', 4500);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (9, 'bk_t_21', 6000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (9, 'bk_t_22', 3000);

INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (10, 'bk_t_23', 4500);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (10, 'bk_t_24', 8000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (10, 'bk_t_25', 3500);

INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (11, 'bk_t_26', 4000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (11, 'bk_t_27', 6000);

INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (12, 'bk_t_28', 3000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (12, 'bk_t_29', 4000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (12, 'bk_t_30', 6000);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (12, 'bk_t_31', 3500);
INSERT INTO BOOK(AUTHOR_ID, TITLE, PRICE) VALUES (12, 'bk_t_32', 4500);
